variables:
  GIT_STRATEGY: fetch

stages:
 - prepare
 - deploy
 - test

kill_and_rsync:
  stage: prepare
  only:
    - master
  tags:
    - ssh_depoloy_vagga_front
  script:
    - $(kill $(screen -S vagga_home_atticlab_eos_wallet -Q echo '$PID')) || echo "No screen session found"
    - $(screen -wipe) || echo "No screen session found"
    - rsync -avr ./ /var/www/atticlab_eos_wallet

screen:
  stage: deploy
  only:
    - master
  tags:
    - ssh_depoloy_vagga_front
  script:
    - cd /var/www/atticlab_eos_wallet
    - screen -dmS vagga_home_atticlab_eos_wallet vagga run_mainnet
    - echo "running ..."

testing:
  tags:
    - ssh_depoloy_vagga_front
  stage: 'test'
  script:
    - echo "test"
