version: '2'
services:
  nodejs:
    container_name: eoswallet-frontend-nodejs-dev
    build: docker/nodejs
    volumes:
      - ./:/src
      - ./logs/nodejs:/logs
    logging:
      options:
        max-size: 50m
    env_file:
      - .env

  nginx:
    restart: always
    container_name: eoswallet-frontend-nginx-dev
    image: nginx:latest
    dns: 8.8.8.8
    ports:
      - "8080:80"
    volumes:
      - ./dist:/dist
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    logging:
      options:
        max-size: 50m

  server:
    restart: always
    container_name: eoswallet-server-dev
    build: docker/server
    ports:
    - "3000:3000"
    volumes:
      - ./:/src
      - ./logs/server:/logs
    logging:
      options:
        max-size: 50m
    env_file:
      - .env
