version: '2'
services:
  db:
    restart: always
    ports:
      - "5435:5432"
    container_name: eoswallet-db-dev
    build: docker/postgres
    volumes:
      - storage:/var/lib/postgresql/data
      - ./logs/postgres/:/logs
      - ./backups/:/backups
#      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    env_file:
      - ./.env
    logging:
      options:
        max-size: 50m

  nodejs:
    container_name: eoswallet-frontend-nodejs-dev
    build: docker/nodejs
    volumes:
      - ./:/src
      - ./logs/nodejs:/logs
    command: ["/entrypoint_stage.sh"]
    links:
      - db
    logging:
      options:
        max-size: 50m
    env_file:
      - .env

  nginx:
    restart: always
    container_name: eoswallet-frontend-nginx-dev
    image: nginx:latest
    dns: 8.8.8.8
    ports:
      - "8080:80"
    volumes:
      - ./dist:/dist
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    logging:
      options:
        max-size: 50m

  server:
    restart: always
    container_name: eoswallet-server-dev
    build: docker/server
    ports:
    - "3001:3000"
    volumes:
      - ./:/src
      - ./logs/server:/logs
    logging:
      options:
        max-size: 50m
    env_file:
      - .env

volumes:
  storage:
