version: '2'
services:
  db:
    restart: always
    ports:
      - "5434:5432"
    container_name: eoswallet-db
    build: docker/postgres
    volumes:
      - storage:/var/lib/postgresql/data
      - ./logs/postgres/:/logs
      - ./backups/:/backups
#      - ./docker/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    env_file:
      - ./.env
    logging:
      options:
        max-size: 50m

  nodejs:
    container_name: eoswallet-frontend-nodejs
    build: docker/nodejs
    volumes:
      - ./:/src
      - ./logs/nodejs:/logs
    command: ["/entrypoint.sh"]
    logging:
      options:
        max-size: 50m
    env_file:
      - .env

  nginx:
    restart: always
    container_name: eoswallet-frontend-nginx
    image: nginx:latest
    dns: 8.8.8.8
    ports:
      - "8082:80"
    volumes:
      - ./public:/dist
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    logging:
      options:
        max-size: 50m

  server:
    restart: always
    container_name: eoswallet-server
    build: docker/server
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ./:/src
      - ./logs/server:/logs
    logging:
      options:
        max-size: 50m
    env_file:
      - .env

volumes:
  storage:
