version: '2'
services:
  nodejs:
    container_name: eoswallet-frontend-nodejs
    build: docker/nodejs
    volumes:
      - ./:/src
      - ./logs/nodejs:/logs
    logging:
      options:
        max-size: 50m

  nginx:
    restart: always
    container_name: eoswallet-frontend-nginx
    image: nginx:latest
    dns: 8.8.8.8
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/src
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    links:
     - nodejs
    logging:
      options:
        max-size: 50m
