export default {
  SET_SCATTER: 'setScatter',
  SET_EOS_JS: 'setEosjs',
  SET_EOS_JSAPI: 'setEosjsApi',
  SET_IDENTITY: 'setIdentity',
  SET_IDENTITY_ACCOUNT: 'setIdentityAccount',
  SET_EOS_ACCOUNT: 'setEosAccount',
  SET_BALANCE: 'setBalance',
  SET_TRANSACTION: 'setTransaction',
  SET_TOKENLIST: 'setTokenList',
  SET_TOKENBALANCE: 'setTokenBalance',
  SET_AIRGRABS: 'setAirgrabs',
  SET_ACTIONINFOPOPUP: 'setActionInfoPopUP',
  SET_HARDWARE: 'setHardware',
  SET_LEDGER_WALLET: 'setLedgerWallet',
  LOGOUT: 'logoutScatter',
  SET_NODE: 'setNode',
  RELOGIN_SCATTER_EOS: 'reloginScatterEos',
};
